### ISSUE TITLE
lein ring uberwar => No such var: tf/parse-local-date

### ISSUE THREAD

**Issue by jsyrjala** [metosin/compojure-api-examples#1]
Somehow lein ring uberwar tries to use old version of clj-time (pre 0.6.0). Adding                  [clj-time "0.6.0"] to dependencies fixes this.

```
% lein ring uberwar
Exception in thread "main" java.lang.RuntimeException: No such var: tf/parse-local-date, compiling:(ring/swagger/coerce.clj:14:25)
    at clojure.lang.Compiler.analyze(Compiler.java:6380)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
```

**Comment by freckletonj** [comment]
I'm getting this error again with a stock `lein new compojure-api my-app`...

**Comment by ikitommi** [comment]
Hmm... try `lein deps :tree` and check what version of `clj-time` you are having. There should be version `[clj-time "0.12.0"]`. You might have some other dependency which drags older version of the lib. Adding a direct dependency to `[clj-time "0.12.0"]` should help.

**Comment by srinidagda** [comment]
I'm getting this error when running `lein new compojure-api my-app`
Exception in thread "main" java.lang.AbstractMethodError: Method compojure/api/routes/Route.invoke()Ljava/lang/Object; is abstract, compiling:(/private/var/folders/sc/_5vqrzqd6957db1699lb0lm00000gq/T/form-init5955368636245682796.clj:1:125)
